vfs clean
kinode-dao/kinode pull request #38
Opened 2023-10-25 15:34 UTC by barraguda

currently: 
- prepends / appends '/' to files or directories that don't have them
- returns template errors instead of panics

todo:
- revamp types (specifically errors) to include inner strings, return them intelligently [x]
- implicit directory creation with /newdir1/newfile1.txt creates newdir1 if it doesn't exist, should probably work for nested things too [x]

2023-11-01 17:41 UTC, nick1udwig requested changes
Looks a lot nicer than before. Left a few comments.

For future work (not this PR), would be nice to update names internal to vfs to match better: some have been left behind. E.g., within we refer to the "hash" of a file in fs, but those are no longer hashes. Another example: we now refer to "vfss" as "drives".

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +    let (_key, children) = {
Remove `_key` here and below at 148.

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +            HashSet::new()
Change to `return Ok(())`

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +    vfs: Arc<Mutex<Vfs>>,
Consider changing `rename_entry()` to take a `MutexGuard` like in `create_entry()`: create code is more readable than rename.

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +                        return Err(VfsError::InternalError);
Are these appropriate uses of InternalError? Seems like this is a user input error, not an InternalError?

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +                Err(_) => return Err(VfsError::PersistError),
This and other calls to persist_state() seem like they can just `?` since persist_state() returns PersistError itself.

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +            match persist_state(send_to_persist, &mut recv_response, id).await {
Do we actually need to persist_state here?

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +            match persist_state(send_to_persist, &mut recv_response, id).await {
Same as in WriteOffset case: do we really need this?

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +            match persist_state(send_to_persist, &mut recv_response, id).await {
Same as in WriteOffset case: do we really need to persist?

2023-11-01 17:41 UTC, nick1udwig commented on src/vfs.rs
> +        let new_child_path = old_child_path.replace(old_path, new_path);
Has this been tested? It looks to me like this will not update the full_path stored in the entry.

2023-11-01 23:56 UTC, barraguda commented on src/vfs.rs
> +    vfs: Arc<Mutex<Vfs>>,
there is probably a good way to do this that I've yet to figure out, but currently I need this because there's a loop of recursion within the recursion itself, every affected rename entry might have children itself

2023-11-01 23:59 UTC, barraguda commented on src/vfs.rs
> +        let new_child_path = old_child_path.replace(old_path, new_path);
this is tested and works (now), but there's one thing left which I wonder how I should handle, the case where:

rename `/dir1/dir2/note` to `/dir1/dir2/dir3/note2`, or other implicit moving a file to another directory. I think we might want to limit renames to specific items and restrict moves, even though we could recursively loop and rename/create where needed

2023-11-02 00:07 UTC, nick1udwig commented on src/vfs.rs
> +        let new_child_path = old_child_path.replace(old_path, new_path);
The case you mention is not a rename imo: that's a move. A rename is `/foo/bar/` -> `/foo/baz/` or `/foo/bar.txt` -> `/foo/lol.txt`.

2023-11-02 00:07 UTC, nick1udwig commented
I'm going to do a quick test and then will approve.

2023-11-02 04:07 UTC, nick1udwig commented on src/vfs.rs
> +    vfs: Arc<Mutex<Vfs>>,
That's fine, leave as is.

2023-11-02 04:08 UTC, nick1udwig commented on src/vfs.rs
> +        let new_child_path = old_child_path.replace(old_path, new_path);
Confirmed this works.

2023-11-02 04:10 UTC, nick1udwig approved these changes
Please address last two comments added just now, then ready for merge.

Really nice work, thanks @bitful-pannul !

2023-11-02 04:10 UTC, nick1udwig commented on src/vfs.rs
>      if expects_response.is_some() {
This should be updated to work properly if rsvp is set but expects_response is not.

2023-11-02 04:10 UTC, nick1udwig commented on src/vfs.rs
>      if expects_response.is_some() {
Also: it would probably be good to print_to_terminal verbosity 1 the ipc in the case that no response is sent.

2023-11-02 15:18 UTC, barraguda commented on src/vfs.rs
>      if expects_response.is_some() {
cheers!

2023-11-02 15:19 UTC, merged